### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pfvbell** [tk42/streamlit-draggable-list#3]
Your example gives this error:
![image](https://github.com/tk42/streamlit-draggable-list/assets/64703156/7ad90482-0baf-453c-8c5f-eaa15e14395e)

**Comment by jvollmuller-risk** [comment]
Got the same error!

**Comment by tk42** [comment]
As you can see .devcontainer, this repository is intended to use Python3.10.

The error message you provided, `TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'`, suggests that you're trying to use the `|` (bitwise OR) operator with operands that are not supported. Specifically, one of the operands seems to be of `type` and the other is `NoneType`.

The common mistake is often seen in the context of Python type hints, especially in Python 3.9+ when using the new union operator `|` for type hinting.

Ensure that you're using Python 3.9 or newer.

**Comment by NicolaGugole** [comment]
Hi! I am using Python 3.9.18 and getting the same error. The Pypi page explicits the need of Python>=3.6, please update it to a minimum working version.
